### ISSUE TITLE
add pls

### ISSUE THREAD

**Issue by AVuTuVA** [MrTronMan/Amend#1]
add pls https://ci.codemc.io/job/etil2jz/job/Mirai-1.19/ and https://ci.pufferfish.host/ and https://github.com/Bloom-host/Petal/releases

**Comment by MrTronMan** [comment]
Hi! Thanks for using my plugin, so to clarify you would like me to add pufferfish specifically? @AVuTuVA

**Comment by MrTronMan** [comment]
Closed due to inactivity.
