### ISSUE TITLE
Alternative to hot swapping

### ISSUE THREAD

**Issue by Spejik** [MrTronMan/Amend#2]
I wanted to use this plugin, but I don't really need the server to update every time purpur updates (which is quite often tbh)

My server restarts everyday at 3am, so I thought there could be an option to make the plugin only check for newer version when the server starts. If there's a newer version it would download it and restart the server. (or just hotpatch it as it does now)

I'm not sure if restarting is possible in normal java, but I think with spigot you can use the "restart-script" in config?

**Comment by MrTronMan** [comment]
The plugin only activates on a shutdown (or a reload), it updates after all the plugins shutdown and there is a VERY low chance that anything COULD happen. Also most hosts do not allow you to modify nor create another restart script, or even upload a `.sh` file. Unless I am not understanding your question correctly..please lmk thx 😁 

@Spejik

**Comment by Spejik** [comment]
I didn't know it only updates on shutdown, in that case I will close this issue.
You might wanna update the readme, currently it sounds like it hotpatches the jar whenever a new version comes out 😄

**Comment by MrTronMan** [comment]
I'll be sure to add it to the readme, sorry about that! Thanks for using Amend!
