### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by Fumiyoo** [MrTronMan/Amend#9]
As of right now, I'm unable to download any version of Amend.

To reproduce:
1. https://amend.mrtron.dev/download/
2. Click the download button of any version
3. Wait to be redirected

![image](https://github.com/MrTronMan/Amend/assets/65785173/3b085934-0c47-473b-a8e1-8de1f8e77260)

**Comment by MrTronMan** [comment]
Hi, sorry for the late response, this might have been just a bad chance with the webserver. Apologies, should work!

**Comment by MrTronMan** [comment]
Please let me know if you are able to download.

**Comment by MrTronMan** [comment]
Automatically assumed as resolved.
